name: acore
version: '${version}'
main: org.antagon.acore.Acore
api-version: '1.21'
authors: [ bloodysupport, utophii ]
description: Multi-purpose plugin for Antagon:Reborn server
website: https://reborn.antagon.su

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: false
    ConditionalEvents:
      load: BEFORE
      required: false
    MythicMobs:
      load: BEFORE
      required: false
    PacketEvents:
      load: BEFORE
      required: false
    CoreProtect:
      load: BEFORE
      required: false
    CoinsEngine:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
permissions:
  permission.admin:
    description: Permission for admin commands
    default: op
    children:
      - acore.showinfo
      - acore.link
      - acore.admin
      - acore.fairplay.bypass
  acore.showinfo:
    description: Permission for showinfo command
    default: true
  acore.link:
    description: Permission for link command
    default: true
  acore.admin:
    description: Permission to reload the plugin and manage acore
    default: op
  acore.fairplay.bypass:
    description: Permission to bypass Xaero's Minimap fairplay mode enforcement
    default: op