name: acore
version: '${version}'
main: org.antagon.acore.Acore
api-version: '1.21'
load: STARTUP
authors: [ bloodysupport, utophii ]
description: Multi-purpose plugin for Antagon:Reborn server
website: https://reborn.antagon.su

depend: [LuckPerms]
softdepend: [ConditionalEvents, MythicMobs]

commands:
  showinfo:
    description: Toggleable bossbar
    usage: /showinfo
    permission: acore.showinfo
  link:
    description: Invite a player to become your referral
    usage: /link <player>
    permission: acore.link

permissions:
  permission.admin:
    description: Permission for admin commands
    default: op
    children:
      - acore.showinfo
      - acore.link
  acore.showinfo:
    description: Permission for showinfo command
    default: true
  acore.link:
    description: Permission for link command
    default: true